"""Markdown renderer — ported from ReplexAgent's MarkdownRenderer.js."""
from __future__ import annotations

import re


class MarkdownRenderer:
    format = "markdown"
    mime_type = "text/markdown"

    def render(self, data: dict) -> dict:
        parts = [
            f"# {data['title']}",
            "",
            f"**Source:** {data.get('url', 'N/A')}  ",
            f"**Generated:** {data['generatedAt']}",
            "",
            self._confidence_block(data["overallConfidence"], "Overall Confidence"),
            "",
            self._executive(data["executive"]),
            "",
            self._developer(data["developer"]),
            "",
            self._business(data["business"]),
            "",
            self._roadmap(data["roadmap"]),
            "",
            "---",
            f"*Report generated by the AI Analysis Agent (Kimi K2). "
            f"Confidence: {round(data['overallConfidence']['score'] * 100)}% — "
            f"{data['overallConfidence']['rationale']}*",
        ]
        content = "\n".join(parts)
        return {
            "format": self.format,
            "content": content,
            "filename": self._slugify(data.get("projectName", "report")) + ".md",
            "mimeType": self.mime_type,
            "sizeBytes": len(content.encode("utf-8")),
        }

    def _confidence_block(self, confidence: dict, label: str) -> str:
        pct = round(confidence["score"] * 100)
        lines = [f"> **{label}: {pct}%** — {confidence['rationale']}"]
        if confidence["excludedDataPoints"]:
            lines.append(f">\n> _Excluded ({len(confidence['excludedDataPoints'])}):_")
            for e in confidence["excludedDataPoints"][:10]:
                lines.append(f"> - {e}")
        return "\n".join(lines)

    def _executive(self, exec_data: dict) -> str:
        sev = exec_data["bySeverity"]
        sev_line = " · ".join(f"**{k.title()}:** {v}" for k, v in sev.items() if v > 0) or "No findings"
        cat = exec_data["byCategory"]
        cat_lines = "\n".join(f"| {k.replace('-', ' ').title()} | {v} |" for k, v in cat.items() if v > 0)

        return "\n".join([
            "## Executive Summary",
            "",
            exec_data["overview"],
            "",
            f"- **Overall Risk:** {exec_data['overallRisk']}",
            f"- **Total Findings:** {exec_data['totalFindings']}",
            f"- **Estimated Timeline:** {exec_data['estimatedTimeline']}",
            f"- **Top Action:** {exec_data['topAction']}",
            "",
            f"**By Severity:** {sev_line}",
            "",
            "**By Category:**",
            "",
            "| Category | Count |",
            "|---|---|",
            cat_lines,
            "",
            self._confidence_block(exec_data["confidence"], "Section Confidence"),
        ])

    def _developer(self, dev: dict) -> str:
        lines = [
            "## Developer Report",
            "",
            dev["overview"],
            "",
            f"**Technical Debt:** {dev['technicalDebt']}",
            "",
            "**Quick Wins:**",
        ]
        if dev["quickWins"]:
            lines += [f"- {q}" for q in dev["quickWins"]]
        else:
            lines.append("- None identified")

        lines.append("")
        lines.append("### Finding Groups")
        for g in dev["groups"]:
            lines.append(f"\n#### {g['name']} ({g['count']} findings) — max severity: {g['maxSeverity']}")
            for f in g["findings"]:
                file_note = f" (`{f['file']}`)" if f.get("file") else ""
                lines.append(f"- **[{f['severity'].upper()}] {f['title']}**{file_note}")
                lines.append(f"  - {f['description']}")
                lines.append(f"  - *Recommendation:* {f['recommendation']}")

        lines.append("")
        lines.append(self._confidence_block(dev["confidence"], "Section Confidence"))
        return "\n".join(lines)

    def _business(self, biz: dict) -> str:
        lines = [
            "## Business Summary",
            "",
            biz["overview"],
            "",
            f"- **Total Effort:** {biz['totalEffortHours']}h",
            f"- **Estimated Cost:** ${biz['estimatedCost']:,}",
            "",
            f"**ROI:** {biz['roi']}",
            "",
            "**Impact Summary:**",
            "",
            "| Finding | Severity | Effort | Hours | Priority |",
            "|---|---|---|---|---|",
        ]
        for item in biz["impactSummary"]:
            lines.append(
                f"| {item['title']} | {item['severity']} | {item['effort']} | "
                f"{item['effortHours']}h | {item['priorityScore']:.1f} |"
            )
        lines.append("")
        lines.append(self._confidence_block(biz["confidence"], "Section Confidence"))
        return "\n".join(lines)

    def _roadmap(self, roadmap: dict) -> str:
        lines = [
            "## Implementation Roadmap",
            "",
            roadmap["overview"],
            "",
            f"- **Total Hours:** {roadmap['totalEstimatedHours']}h",
            f"- **Timeline:** {roadmap['estimatedTimeline']}",
        ]
        for p in roadmap["phases"]:
            lines.append(f"\n### {p['name']} ({p['timeframe']}) — {p['totalHours']}h")
            lines.append(p["description"])
            for item in p["items"]:
                lines.append(f"- **{item['title']}** ({item['effort']}, {item['effortHours']}h): {item['action']}")
        lines.append("")
        lines.append(self._confidence_block(roadmap["confidence"], "Section Confidence"))
        return "\n".join(lines)

    @staticmethod
    def _slugify(text: str) -> str:
        return re.sub(r"^-|-$", "", re.sub(r"[^a-z0-9]+", "-", text.lower()))
